# Generated by Django 4.1.2 on 2022-11-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeBook', '0003_ingredient_recipeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Notes',
            field=models.CharField(default='null', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='Preparation',
            field=models.CharField(default='null', max_length=2000),
            preserve_default=False,
        ),
    ]
